# -*- mode: ruby -*-
# vi: set ft=ruby :

$mininet = <<SCRIPT
  echo "mininet"
  git clone git://github.com/mininet/mininet
  pushd mininet
  git checkout 2.2.2
  echo "Patching util/install.sh to use iproute2 instead of iproute"
  sed -i 's/iproute /iproute2 /g' util/install.sh
  ./util/install.sh -fnv
  popd
SCRIPT

$python = <<SCRIPT
  echo "pip"
  sudo apt-get update
  sudo apt-get install -y python-pip
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      v.customize ["modifyvm", :id, "--memory", "2048"]
  end

  ## Provisioning
  config.vm.provision :shell, privileged: false, :inline => $mininet
  config.vm.provision :shell, privileged: false, :inline => $python

  ## SSH config
  config.ssh.forward_x11 = false

end
